name: wise-env
channels:
  - pytorch
  - conda-forge
  - fastai
  - defaults
dependencies:
  - conda=4.10.3
  - jupyter=1.0.0
  - jupyterlab
  - matplotlib=3.4.3
  - pandas=1.3.3
  - pip=21.2.4
  - pysoundfile=0.10.3
  - python=3.9.7
  - python-docx=0.8.11
  - pytorch=1.9.0
  - scikit-learn
  - seaborn=0.11.2
  - torchaudio=0.9.0
  - torchvision=0.2.2
  - transformers=4.10.2
  - nbdev
  - datasets
  - librosa
  - docx2txt
