# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"getText": "10-process-data.ipynb",
         "docx_to_df": "10-process-data.ipynb",
         "find_timestamp": "10-process-data.ipynb",
         "add_splits": "12-training-dev-test.ipynb",
         "check_label": "42-wav-embedding-preprocess.ipynb",
         "check_ts": "13-validate-csv.ipynb",
         "to_millseconds": "42-wav-embedding-preprocess.ipynb",
         "short_warning": "42-wav-embedding-preprocess.ipynb",
         "preprocess_audio_segments_csv": "42-wav-embedding-preprocess.ipynb",
         "add_audio_embeddings_info": "42-wav-embedding-preprocess.ipynb",
         "write_nd_parquet": "42-wav-embedding-preprocess.ipynb",
         "get_umap_fit": "44-wav-embedding-experiments-dev.ipynb",
         "show_umap_dims": "44-wav-embedding-experiments-dev.ipynb",
         "get_kmeans_clusters": "44-wav-embedding-experiments-dev.ipynb",
         "get_fixed_length_segments": "45-restructure-audio-fixed-length.ipynb",
         "short_embedding_csv_load": "45-restructure-audio-fixed-length.ipynb",
         "timestamp2index": "50-audio-training.ipynb",
         "zsresults_to_df": "90-general-metrics-evaluation.ipynb",
         "get_performance_metrics": "90-general-metrics-evaluation.ipynb"}

modules = ["text_preprocessing.py",
           "audio_preprocessing.py",
           "audio_embedding_viz.py",
           "audio_modeling.py",
           "performance_metrics.py"]

doc_url = "https://vanderbilt-data-science.github.io/wise/"

git_url = "https://github.com/vanderbilt-data-science/wise/tree/main/"

def custom_doc_links(name): return None
